### ISSUE TITLE
change product img size in email template 

### ISSUE THREAD

**Issue by bloggerpact** [mage-mzax/emarketing#11]
Hey,

is there any way to change product size in email ? (currently it is 120 which is too small)

I tried to make img size bigger using : 

`"<td class="product-image" width="320" valign="middle">
            <img alt="<?php echo $item->getName() ?>" src="<?php echo $this->getProductImage($item) ?>" />
        </td>"`

but still img render 120 img. please help me out to make img size bigger 
thanks in advance

**Comment by jsiefer** [comment]
Hi @bloggerpact 

The method footprint allows a second and third argument `getProductImage($object, $attribute = 'small_image', $size = 100)` maybe that will help. Also have a look at the final rendered result to see if there are any CSS classses that alter the look.
