### ISSUE TITLE
Editor don't loaded

### ISSUE THREAD

**Issue by danielchicote** [mage-mzax/emarketing#2]
Hello Jacob and congratulations, the module looks incredible.

I have a problem with the content editor because dont load the contents, is always looped looking for this two files: 

![emarketing-screenshot](https://cloud.githubusercontent.com/assets/7643167/10914344/4c933b1a-8252-11e5-8845-6af70cc86c96.jpg)

![404](https://cloud.githubusercontent.com/assets/7643167/10914668/b0f42258-8253-11e5-9b5e-a784e6431f28.jpg)

Is only a routing problem.

**Comment by jsiefer** [comment]
Hi Daniel,
thanks for your feedback, glad you like it.

I am having trouble re-producing your issue. Can you confirm the files are loading when accessed directly from the browser. Can you double check that they are in the right place.

Could you send the request headers if it still fails.
- yourdomain.com/js/mzax/ckeditor/ckeditor.js
- yourdomain.com/skin/adminhtml/default/default/mzax/editor.css

**Comment by danielchicote** [comment]
In the production server the module works perfectly, but in my localhost this two files are requested to htttp://localhost/js and http://localhost/skin respectively, when the installation is located in http://localhost/magento

**Comment by jsiefer** [comment]
right okay, try the file from the commit above, it should fix the issue. Let me know how it went.

**Comment by danielchicote** [comment]
Perfect.
