### ISSUE TITLE
Emailing issue

### ISSUE THREAD

**Issue by imsamthomas** [mage-mzax/emarketing#3]
I have tested this extesion on my server.
The email is not working.
I tried :
- PHP email: not email sent
- SMTP: Mandrill: **Failed** in Outbox : The API is correct.

Both does not work, in Outbox it said **Sent**

Please help

**Comment by jsiefer** [comment]
Hi can you check the Magento logs in var/log for any issues.

Do you have access to the database, then check the table mzax_emarketing_email_outbox and the log column. I just published a new release (0.4.7) which will show the value in the admin panel.

**Comment by samnguyen80** [comment]
Thanks for reply.
I trace and test a lot with this.

The main problem is that our Server has been blocked outbound connections on port: 465 or 587 25 by Gcloud https://cloud.google.com/compute/docs/tutorials/sending-mail/
I found some other cloud services are doing like this.

The log shows: 

```
2015-12-01T10:28:46+00:00 DEBUG (7): Send Message: #19 - 
2015-12-01T10:29:38+00:00 DEBUG (7): Send Message: #20 - 
```

I tried SMPT Pro or your Built-in SMTP did not work except for Google Apps.
This [Mandrill!](http://www.magentocommerce.com/magento-connect/ebizmarts-magemonkey-official-mailchimp-and-mandrill-extension.html) works because they are using API not SMTP protocol.
Hope you can integrate with this module.

**Comment by jsiefer** [comment]
Hey Michael, okay makes sense what you are saying. I used the SMTP API as it was quick and easy to add. Maybe as a quick fix; have a look at the [Mandrill Transport class](https://github.com/mage-mzax/emarketing/blob/master/src/module/Model/Outbox/Transporter/Mandrill.php#L35,L36) and change the `PORT = 2525` and disable `SSL = false`. If ssl is a must for you then this does not work. Let me know if that works.

I will still look into the API function and try to work something out.

**Comment by samnguyen80** [comment]
Hi,

I tried **Port 2525** but does not work with Mandrill.
I think we have to find API solution.

Anyway, We can use Magemonkey (included Mandrill) for emailer.
By default, Magemonkey catch send email event for every transactional email on a store. 
So why not use Magento default email? If so it will work with Mandrill API.

**Comment by jsiefer** [comment]
Hey Michael, I added an email transport for the API, do you think you can install the files from the above commit and test it out?
I tested it in an test environment and it seems to work. Let me know how it goes.
thanks

**Comment by samnguyen80** [comment]
Yes, I can.
I will update you when have new information.

**Comment by jsiefer** [comment]
Hi Michael, have you had chance to try it out yet?

**Comment by samnguyen80** [comment]
Thanks for your update.
We are running a big project. I will try as soon as I can. I think everything is okay as I see in the code.

**Comment by jsiefer** [comment]
no worries, Ill close this issue then, feel free to reopen it if there is anything wrong with it.

**Comment by samnguyen80** [comment]
I haved updated and test, using Mandrill API.
It did not work even in local. I filled correct API key.
![2015-12-25_1737](https://cloud.githubusercontent.com/assets/2810172/12002340/32d11e54-ab2e-11e5-9dd3-7f5f5950138b.png)

If I use different transporter, it is okay.
There is no log :(

**Comment by jsiefer** [comment]
Hi Michael,

I checked again and it works fine. Never the less I re-factored the implementation and added an API test call to the configuration so it will show you if there is any issue with the API key or any settings and also improve the logging.
Also try to check the mzax_emarketing.log
