### ISSUE TITLE
Campaign Preview (Connection Reset Error)

### ISSUE THREAD

**Issue by yazicierh** [mage-mzax/emarketing#5]
used configuration is:

wampserver 2.5
php v. 5.5.12
apache 2.4.9

site url : websitename:8080/magento1/

magento 1.9.2.4

**Comment by yazicierh** [comment]
I think it is wamp issue or base url issue,
 there is no problem at IIS 7 PHP 5.5.30

**Comment by jsiefer** [comment]
I have been running it using different configurations with no problem. 
Where you apple to solve it?
