### ISSUE TITLE
Warning: include tracker/new or edit tracker

### ISSUE THREAD

**Issue by rskonieczka** [mage-mzax/emarketing#6]
Hi ,

I'm trying to use your extension. Please help me. 

`Warning: include(/public_html/includes/src/z6zjfr_jinhp4muczl4tybbkadnpceg5cbm_7v_30pjzcdms0.php): failed to open stream: No such file or directory  in /home/coralvalue/domains/venolshop.com/public_html/includes/src/Varien_Autoload.php on line 94`

```
#1 ...public_html/includes/src/Varien_Autoload.php(94): Varien_Autoload::autoload()
#2 [internal function]: Varien_Autoload->autoload('z6zjfr_jinhp4mu...')
#3 [internal function]: spl_autoload_call('z6zjfr_jinhp4mu...')
```

Magento ver. 1.9.2.4

Best regards
BTW. Good job

**Comment by jsiefer** [comment]
Cannot reproduce, sorry
Error message does not seem to be associated with this extension.
Feel free to reopen it with more information .
