### ISSUE TITLE
Lack of function ispurged()

### ISSUE THREAD

**Issue by ilgujo** [mage-mzax/emarketing#8]
Hi,
When we try to preview in web browser we get an error in Magento and this is what we find in the report:

a:5:{i:0;s:71:"Invalid method Mzax_Emarketing_Model_Outbox_Email::isPurged(Array.....

We just added this function to the end of 
app/code/community/Mzax/Emarketing/Model/Outbox/Email.php
    public function isPurged()
    {
        return (bool) $this->getData('purged');
    }
before last }
and preview in web browser is working now.
We use last version of Mzax Emarketing 0.4.9

**Comment by jsiefer** [comment]
Thanks @ilgujo , I added the missing method to the email model
